name: Deploy to Server

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy updated files via rsync
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 5.161.100.34
          username: zubair
          password: CvWq21Ws0dcS9
          port: 22
          script: |
            rsync -avz --progress --update ./ /var/www/html/
            sudo chmod -R 755 /var/www/html
            sudo chown -R www-data:www-data /var/www/html
